import { TableDef, ColumnDef } from "../parser";
import { TableDescription } from "../ai/client";

/**
 * Generate DATA_DICTIONARY.md combining parsed table structure with AI descriptions.
 */
export function generateDictionaryMarkdown(
  tables: TableDef[],
  descriptions: TableDescription[]
): string {
  const descMap = new Map(descriptions.map((d) => [d.name, d]));

  const lines: string[] = [];

  lines.push("# Data Dictionary");
  lines.push("");
  lines.push("> Auto-generated by [Schemalog](https://github.com/schemalog). Do not edit manually.");
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("## Table of Contents");
  lines.push("");

  for (const table of tables) {
    lines.push(`- [${table.name}](#${table.name.toLowerCase()})`);
  }

  lines.push("");
  lines.push("---");
  lines.push("");

  for (const table of tables) {
    const desc = descMap.get(table.name);

    lines.push(`## ${table.name}`);
    lines.push("");

    if (desc?.description) {
      lines.push(`${desc.description}`);
      lines.push("");
    }

    lines.push("| # | Column | Type | Nullable | Default | Description |");
    lines.push("|---|--------|------|----------|---------|-------------|");

    const colDescMap = new Map((desc?.columns || []).map((c) => [c.name, c.description]));

    let idx = 0;
    for (const col of table.columns) {
      idx++;
      const nullable = col.nullable ? "YES" : "NO";
      const defaultVal = col.defaultValue || (col.nullable && !col.defaultValue ? "NULL" : "-");
      const aiDesc = colDescMap.get(col.name) || "-";

      lines.push(
        `| ${idx} | \`${col.name}\` | ${escapePipe(col.type)} | ${nullable} | ${escapePipe(defaultVal)} | ${escapePipe(aiDesc)} |`
      );
    }

    lines.push("");

    // Primary key info
    if (table.primaryKey.length > 0) {
      lines.push(`**Primary Key**: ${table.primaryKey.map((k) => `\`${k}\``).join(", ")}`);
      lines.push("");
    }

    // Index info
    if (table.indexes.length > 0) {
      lines.push("**Indexes**:");
      for (const idx of table.indexes) {
        lines.push(`- \`${idx}\``);
      }
      lines.push("");
    }

    lines.push("---");
    lines.push("");
  }

  return lines.join("\n");
}

function escapePipe(val: string): string {
  return val.replace(/\|/g, "\\|");
}
