import { TableDiff } from "../diff";

/**
 * Format schema diffs as a Markdown report suitable for PR comments.
 */
export function formatDiffMarkdown(diffs: TableDiff[], currentRef: string, baseRef: string): string {
  const lines: string[] = [];

  lines.push("# Schema Diff");
  lines.push("");
  lines.push(`**Base**: \`${baseRef}\` → **Current**: \`${currentRef}\``);
  lines.push("");

  // Summary
  const added = diffs.filter((d) => d.status === "added");
  const removed = diffs.filter((d) => d.status === "removed");
  const modified = diffs.filter((d) => d.status === "modified");
  const changed = [...added, ...removed, ...modified];

  if (changed.length === 0) {
    lines.push("✅ **No schema changes detected.**");
    lines.push("");
    return lines.join("\n");
  }

  lines.push("## Summary");
  lines.push("");
  lines.push(`| Type | Count |`);
  lines.push(`|------|-------|`);
  if (added.length) lines.push(`| 🟢 Tables added | ${added.length} |`);
  if (removed.length) lines.push(`| 🔴 Tables removed | ${removed.length} |`);
  if (modified.length) lines.push(`| 🟡 Tables modified | ${modified.length} |`);
  lines.push(`| ⚪ Tables unchanged | ${diffs.length - changed.length} |`);
  lines.push("");

  // Added tables
  for (const d of added) {
    lines.push(`---`);
    lines.push(`## 🟢 \`${d.table}\` — Added`);
    lines.push("");
    lines.push(`| Column |`);
    lines.push(`|--------|`);
    for (const col of d.addedColumns) {
      lines.push(`| \`${col}\` |`);
    }
    lines.push("");
  }

  // Removed tables
  for (const d of removed) {
    lines.push(`---`);
    lines.push(`## 🔴 \`${d.table}\` — Removed`);
    lines.push("");
    lines.push(`| Column |`);
    lines.push(`|--------|`);
    for (const col of d.removedColumns) {
      lines.push(`| \`${col}\` |`);
    }
    lines.push("");
  }

  // Modified tables
  for (const d of modified) {
    lines.push(`---`);
    lines.push(`## 🟡 \`${d.table}\` — Modified`);
    lines.push("");

    if (d.addedColumns.length) {
      lines.push("**Columns added:**");
      for (const col of d.addedColumns) lines.push(`- \`${col}\``);
      lines.push("");
    }

    if (d.removedColumns.length) {
      lines.push("**Columns removed:**");
      for (const col of d.removedColumns) lines.push(`- 🔴 \`${col}\``);
      lines.push("");
    }

    if (d.modifiedColumns.length) {
      lines.push("**Type changed:**");
      lines.push("");
      lines.push(`| Column | Old | New |`);
      lines.push(`|--------|-----|-----|`);
      for (const m of d.modifiedColumns) {
        lines.push(`| \`${m.name}\` | \`${m.oldType}\` | \`${m.newType}\` |`);
      }
      lines.push("");
    }

    if (d.indexChanges.length) {
      lines.push("**Index changes:**");
      for (const idx of d.indexChanges) lines.push(`- \`${idx}\``);
      lines.push("");
    }
  }

  lines.push(`---`);
  lines.push(`*Generated by [Schemalog](https://github.com/KeKeKuKi/schemalog).*`);
  lines.push("");

  return lines.join("\n");
}
